# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-20 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id_hab', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('clima', models.CharField(max_length=20, unique=True)),
                ('vegetacion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HabitatContinente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Continente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zoo.Continente')),
                ('habitat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zoo.Habitat')),
            ],
        ),
    ]
